[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.147.5"
  HUGO_ENV = "production"
  NODE_VERSION = "20"

[context.production.environment]
  HUGO_ENV = "production"

[[redirects]]
  from = "/*"
  query = {ref = ":ref"}
  to = "/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.storypad.me/*"
  to = "https://storypad.me/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://storypad.me/*"
  to = "https://storypad.me/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.storypad.me/*"
  to = "https://storypad.me/:splat"
  status = 301
  force = true
